# Generated by Django 6.0.3 on 2026-03-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('perfil_sensorial', models.TextField(blank=True)),
                ('comunicacao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
