# Generated by Django 6.0.3 on 2026-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ra',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
