# Generated by Django 6.0.3 on 2026-03-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_aluno_ra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='comunicacao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='perfil_sensorial',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
