# Generated by Django 6.0.3 on 2026-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_aluno_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Vídeo')),
                ('youtube_id', models.CharField(max_length=20, verbose_name='ID do Vídeo (ex: dQw4w9WgXcQ)')),
                ('categoria', models.CharField(choices=[('manejo', 'Manejo Comportamental'), ('pedagogico', 'Apoio Pedagógico'), ('atividades', 'Sugestões de Atividades')], max_length=20, verbose_name='Categoria')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
