# Generated by Django 6.0.5 on 2026-05-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(choices=[('video', 'Vídeo'), ('book', 'Livro/Ebook'), ('article', 'Artigo Científico'), ('activity', 'Atividade Pedagógica')], max_length=20, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/Resumo')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources_files/', verbose_name='Arquivo (PDF/Doc)')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Externo/Vídeo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
