# Generated by Django 6.0.5 on 2026-05-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_options_remove_resource_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('estrategia', 'Estratégia'), ('video', 'Vídeo'), ('livro', 'Livro'), ('artigo', 'Artigo'), ('ferramenta', 'Ferramenta')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='file_url',
            field=models.URLField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(),
        ),
    ]
