# Generated by Django 6.0.5 on 2026-05-24 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Diagnóstico/CID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students_photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Estratégia')),
                ('description', models.TextField(verbose_name='Descrição do que funciona')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='É para crises/emergências?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='students.student')),
            ],
            options={
                'verbose_name': 'Estratégia de Acolhimento',
                'verbose_name_plural': 'Estratégias de Acolhimento',
            },
        ),
    ]
