# Generated by Django 6.0.5 on 2026-05-24 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('relationship', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('tutor', 'Tutor/Guardião'), ('outro', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Contato de Emergência Principal?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
